---
- name: Add Kernel Settings
  hosts: all  # You can change this to the target host or group if needed
  become: yes

  tasks:
    - name: Add Kernel Settings to sysctl.d file
      become_user: root
      copy:
        dest: /etc/sysctl.d/kubernetes.conf
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1

    - name: Load Kernel Settings
      become_user: root
      command: sysctl --system
