# generate_vagrantfile.rb

require 'yaml'

# Read the environment file
vm_config_path = ENV['VM_CONFIG_PATH']

env_config = YAML.load_file(vm_config_path)

# Define Vagrantfile
Vagrant.configure("2") do |config|
  env_config['vms'].each do |vm_config|
    config.vm.define vm_config['name'] do |machine|
      machine.vm.box = env_config['common_config']['box']
      machine.vm.network "private_network", ip: vm_config['ip']
      machine.vm.hostname = vm_config['name'] # Set the hostname for the VM

      machine.vm.provider "virtualbox" do |vb|
        vb.memory = env_config['common_config']['memory']
        vb.cpus = env_config['common_config']['cpus']
        vb.name = vm_config['name']
        vb.gui = false
      end

      machine.hostmanager.enabled = true
      machine.hostmanager.manage_host = true 

      # machine.vm.provision "file", source: "./init.sh", destination: "/tmp/init.sh"
      machine.vm.provision "file", source: "./epel.repo", destination: "/tmp/epel.repo"

      machine.vm.provision "shell" do |s|
        s.inline = <<-SCRIPT
          sudo mv /tmp/epel.repo /etc/yum.repos.d/epel.repo
          sudo chown root:root /etc/yum.repos.d/epel.repo
          sudo chmod 644 /etc/yum.repos.d/epel.repo
        SCRIPT
      end

      machine.vm.provision "file", source: env_config['common_config']['ssh_pub_key_source'], destination: env_config['common_config']['ssh_pub_key_dest']

      env_config['vms'].each do |vm|
        machine.vm.provision "shell", inline: <<-SHELL
          #echo "#{vm['ip']} #{vm['name']}" | sudo tee -a /etc/hosts
          cat #{env_config['common_config']['ssh_pub_key_dest']} >> #{env_config['common_config']['authorized_keys_path']}
        SHELL
      end
    end
  end
end